### ISSUE TITLE
403: No access to Object

### ISSUE THREAD

**Issue by nakagit** [mnemonic-no/act-frontend#2]
Hi 

I searched as following:
Object Type:  ipv4
Object value:  153.148.23.118

but, "403: No access to Object" message popped up.
![190308-0004](https://user-images.githubusercontent.com/10558255/54002287-614cd780-4191-11e9-91f2-62f5c2dbb1d0.png)

![190308-0005](https://user-images.githubusercontent.com/10558255/54002299-6ca00300-4191-11e9-85a3-78a534445381.png)

Please let me know anything I should check.  

Many thanks,
Yuki

**Comment by frbor** [comment]
Hi, this means, as the popup explains, that you either do not have access to any objects with that type / value, or more likely in this case, that it does not exist any object with that type/value at all in the platform.

best regards,
     Fredrik

**Comment by nakagit** [comment]
Hi

Could you please tell me how to put object with type/value?

Kind regards,
Yuki

**Comment by frbor** [comment]
You first need to run a bootstrap of the type system (if you have not already done sone). See documentation [here](https://github.com/mnemonic-no/act-bootstrap).

Then you need to insert some data. The easiest way to do this is to checkout some of the [workers](https://github.com/mnemonic-no/act-workers). From this repository you can for example insert data from Mitre Attack like this:

```
./attack.py  [--proxy-string proxy-host:8080] --act-baseurl http://localhost:3000 --userid 1
```

(The baseurl in the example above and the bootstrap must point to your running ACT instance).

Aft you have the attack data you can for instance choose threat actor and search for `APT29`.

**Comment by nakagit** [comment]
Hi

Thank you so much for your help.  :)

Yes, I run a bootstrap and encountered following error:
/opt/act-workers# `./attack.py --act-baseurl http://localhost:3000 --userid 1`
Traceback (most recent call last):
  File "./attack.py", line 30, in <module>
    from act.helpers import handle_fact
ImportError: cannot import name 'handle_fact' from 'act.helpers' (/usr/local/lib/python3.7/dist-packages/act/helpers.py)

[Background Information]
I installed act-api, seeing https://github.com/mnemonic-no/act-api-python.

I need your help, please.

Kind regards,
Yuki

**Comment by frbor** [comment]
You need to update act-api, since handle_fact is only available in the latest version:

```
pip3 install --upgrade act-api
```

**Comment by nakagit** [comment]
Hi 

Thanks, following command made progress.
However, i've got other error as following:

/opt/act-workers# `./attack.py --act-baseurl http://localhost:3000 --userid 1`
[2019-03-10 21:48:59] app=mitre-attack level=WARNING msg=Cache file /root/act-mitre-attack-notify.cache not found, will be created if necessary
[2019-03-10 21:49:01] app=mitre-attack level=ERROR msg=Request failed: http://localhost:3000/v1/fact, {'json': {'type': 'accomplishes', 'value': '', 'accessMode': 'Public', 'sourceObject': 'technique/.bash_profile and .bashrc', 'destinationObject': 'tactic/persistence', 'bidirectionalBinding': False}}, 404
[2019-03-10 21:49:01] app=mitre-attack level=ERROR msg=Unhandled exception: Traceback (most recent call last):
  File "./attack.py", line 376, in <module>
    main()
  File "./attack.py", line 355, in main
    techniques_notify = add_techniques(client, attack)
  File "./attack.py", line 111, in add_techniques
    .destination("tactic", tactic.phase_name)
  File "/usr/local/lib/python3.7/dist-packages/act/helpers.py", line 32, in handle_fact
    fact.add()
  File "/usr/local/lib/python3.7/dist-packages/act/fact.py", line 389, in add
    return self.__add_fact()
  File "/usr/local/lib/python3.7/dist-packages/act/fact.py", line 410, in __add_fact
    fact = self.api_post("v1/fact", **params)["data"]
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 202, in api_post
    return self.api_request("POST", uri, json=kwargs)
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 194, in api_request
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 68, in request
    "Unknown response error {}: {}".format(res.status_code, res.text))
act.base.ResponseError: Unknown response error 404: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/fact</pre>
</body>
</html>


Traceback (most recent call last):
  File "./attack.py", line 376, in <module>
    main()
  File "./attack.py", line 355, in main
    techniques_notify = add_techniques(client, attack)
  File "./attack.py", line 111, in add_techniques
    .destination("tactic", tactic.phase_name)
  File "/usr/local/lib/python3.7/dist-packages/act/helpers.py", line 32, in handle_fact
    fact.add()
  File "/usr/local/lib/python3.7/dist-packages/act/fact.py", line 389, in add
    return self.__add_fact()
  File "/usr/local/lib/python3.7/dist-packages/act/fact.py", line 410, in __add_fact
    fact = self.api_post("v1/fact", **params)["data"]
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 202, in api_post
    return self.api_request("POST", uri, json=kwargs)
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 194, in api_request
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 68, in request
    "Unknown response error {}: {}".format(res.status_code, res.text))
act.base.ResponseError: Unknown response error 404: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/fact</pre>
</body>
</html>

**How can I fix/avoid above error?**

Many thanks,
Yuki

**Comment by frbor** [comment]
Hi, it does not look like the backend server i listening on localhost port 3000, but something else? If not it is strange that you get 404 on this request.

You should be able to do a direct query like this (to get a listing of all the object types that was added by the boot strap):

```
$ curl --silent -H 'ACT-User-ID: 1' 'http://localhost:3000/v1/objectType' 
{"responseCode":200,"limit":0,"count":40,"size":40,"messages":null,"data":[{"id":"da6d11b3-b3aa-4637-8670-74345d832151","namespace":{"id":"00000000-0000-0000-0000-000000000000","name":"Global"},"name":"mutex","validator":"RegexValidator","validatorParameter":"(.|\\n)*"},{"id":"658c0104-270e-4b54-a0ae-b91fb5592d64","namespace":{"id":"00000000-0000-0000-0000-000000000000","name":"Global"},"name":"campaign","validator":"RegexValidator","validatorParameter":"(.|\\n)*"},{"id":"bdc6f470-f653-437b-8912-43d11d2f5c96","namespace":{"id":"00000000-0000-0000-0000-000000000000","name":"Global"},"name":"certificate","validator":"RegexValidator","validatorParameter":"(.|\\n)*"},{"id":"93a4ef95-7ad8-4180-a645-9b26fbf9731f","namespace":{"id":"00000000-0000-0000-0000-000000000000","name":"Global"},"name":"registryEntry","validator":"RegexValidator","validatorParameter":"(.|\\n)*"},{"id":"96ba0eef-dc1c-40fc-812c-2d9dbb722210", 
(...)
```

**Comment by nakagit** [comment]
Hi, I appreciate for your big help.  :)

/opt/act-workers# `curl --silent -H 'ACT-User-ID: 1' 'http://localhost:3000/v1/objectType' `
 
![190311-0001](https://user-images.githubusercontent.com/10558255/54091863-8a0ae200-43c8-11e9-843e-4965656ff3c5.png)

  
**Anything, I should gather information to resolve? 
Yes, I'm willing to do, please let me know.**

Many thanks,
Yuki

**Comment by frbor** [comment]
This shows that you are trying to connect to the GUI. assume the core platform is listening on another port in your setup?

**Comment by nakagit** [comment]
Hi,

Sorry I didn't get what you mention...
BTW, here is the listening ports below.
![190316-0001](https://user-images.githubusercontent.com/10558255/54464786-72ae6900-47bb-11e9-8e57-bd5ae6c90528.png)


Which port, xxxx, should I connect?
`# curl --silent -H 'ACT-User-ID: 1' 'http://localhost:xxxx/v1/objectType'`

Kind regards,
Yuki

**Comment by frbor** [comment]
Hi Yuki. From the above screenshot I would guess that the backend is running at port 8888.

**Comment by frbor** [comment]
Hi, I have not heard from you after my previous update, so I justed wanted to let you know that we will close this issue unless you have anything more to add.

FYI we are also in the progress of creating some installation docutmentation that shoul be available at https://github.com/mnemnic-no/act in a few weeks.

best regards,

Fredrik

**Comment by frbor** [comment]
Closing issue.

**Comment by nakagit** [comment]
Hi Fredrik,

Thank you so much.  :)

All regards,
Yuki
